
CREATE TRIGGER ADD_BRANCH ON BRANCHES
AFTER INSERT
AS
BEGIN
	DECLARE @X INTEGER
	SET @X=(SELECT BRANCH_ID FROM inserted)
	INSERT INTO INVENTORY VALUES (@X,GETDATE(),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
END

TEST:

INSERT INTO BRANCHES VALUES 
(321,'ASEMAN','Mr.Kashani',25,03132311324,'Isfahan,Hotelpol')

select * from INVENTORY

----------------------------------------------------------------------------------------------

CREATE TRIGGER DELETE_BRANCH ON BRANCHES
AFTER DELETE
AS 
BEGIN
	DECLARE @X INTEGER
	SET @X=(SELECT BRANCH_ID FROM deleted)
	DELETE FROM INVENTORY WHERE INVENTORY.BRANCH_ID=@X
	DELETE FROM SERVICE_FORCE WHERE SERVICE_FORCE.BRANCH_ID=@X

END

TEST:


CREATE TRIGGER DELETE_BRANCH ON BRANCHES
AFTER DELETE
AS 
BEGIN
	DECLARE @X INTEGER
	SET @X=(SELECT BRANCH_ID FROM deleted)
	UPDATE INVENTORY 
	SET COMMODITY_1=-30
	WHERE INVENTORY.BRANCH_ID=@X
	DELETE FROM SERVICE_FORCE WHERE SERVICE_FORCE.BRANCH_ID=@X

END
DROP TRIGGER DELETE_BRANCH

------------------------------------------------------------------------

CREATE TRIGGER UPDATE_SALEORDERDETAIL ON SALESORDERDETAIL
AFTER UPDATE
AS
BEGIN
	DECLARE @X TINYINT
	SET @X=(SELECT FOOD_ID FROM inserted)

	UPDATE FOOD_REPORT 
	SET TOTAL_SALES= TOTAL_SALES+1
	WHERE FOOD_ID=@X
END


------------------------------------------------------------------------

CREATE TABLE SERVICE_FORCE_LOG (
	NATIONAL_CODE INTEGER NOT NULL,
	ID INTEGER NOT NULL,
	NAME_FAMILY VARCHAR(40) NOT NULL,
	GENDER VARCHAR(6) CHECK (GENDER IN ('male','female')) NOT NULL ,
	PHONE_NUMBER BIGINT NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL,
	POSITION VARCHAR(10) CHECK (POSITION IN ('chef','manager','accountant')) NOT NULL,
	BRANCH_ID INTEGER NOT NULL,
	SALARY DECIMAL(10,2) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES (BRANCH_ID)
);	




////////////////////////////////////////
CREATE TRIGGER RETIRED_EMPLOYEE ON SERVICE_FORCE
AFTER DELETE
AS
BEGIN
	DECLARE @ID INT
	SET @ID=(SELECT ID FROM deleted)
	INSERT INTO SERVICE_FORCE_LOG 
		SELECT * 
		FROM deleted
		WHERE ID=@ID

END

TEST:
SELECT *
FROM SERVICE_FORCE_LOG

DELETE FROM SERVICE_FORCE
WHERE ID=5000
